name: BRAD-1
channels:
  - defaults
dependencies:
  - pip
  - requests
  - transformers
  - scikit-learn
  - pip:
    - chromadb
    - tabulate
    - sentence-transformers
    - requests-html
    - torch
    - beautifulsoup4
    - langchain_chroma
    - langchain_community
    - langchain_core
    - langchain_nvidia_ai_endpoints
    - langchain_text_splitters
    - semantic-router
    - lxml_html_clean
    - Bio
    - seaborn
    - gget
    - IPython
    - pandas
