from semantic_router import Route
from semantic_router.layer import RouteLayer
from semantic_router.encoders import HuggingFaceEncoder

routeGget = Route(
    name = 'GGET',
    utterances = [
        'Can you retrieve information on the BRCA1, TP53, and EGFR from the NCBI database?',
        'Find the functional annotations for the APC, KRAS, and MYC in the Ensembl database.',
        'Get the expression profiles for CDK2, CDK4, and CDK6 from the GTEx database.',
        'Look up the ontology terms for the PIK3CA, PTEN, and AKT1 in the Gene Ontology database.',
        'Can you provide the chromosomal locations of the RB1, MDM2, and VHL from the UCSC Genome Browser?',
        'Fetch the mutation data for BRAF, NRAS, and KIT from the COSMIC database.',
        'Retrieve the pathways associated with the JAK2, STAT3, and IL6 from the KEGG database.',
        'Obtain the protein-protein interaction networks for the ESR1, AR, and HER2 from the STRING database.',
        'Can you find the clinical variant information for the CFTR, HBB, and SMN1 in the ClinVar database?',
        'Look up the transcript variants for the ALK, ROS1, and RET in the RefSeq database.',
        'Retrieve the expression data for the BRCA2, CHEK2, and PALB2 from the TCGA database.',
        'Find the genetic associations for the FTO, MC4R, and TCF7L2 in the GWAS Catalog.',
        'Get the protein domain information for the LRRK2, SNCA, and PARK2 from the Pfam database.',
        'Look up the epigenetic modifications for the DNMT1, TET2, and HDAC1 in the Roadmap Epigenomics database.',
        'Can you provide the drug-gene interactions for the CYP2D6, CYP3A4, and CYP2C19 from the PharmGKB database?',
        'Fetch the expression data for the HIF1A, VEGFA, and EPO from the Gene Expression Omnibus (GEO) database.',
        'Retrieve the disease associations for the APP, PSEN1, and PSEN2 from the OMIM database.',
        'Obtain the microRNA targets for the BCL2, BAX, and MCL1 from the miRTarBase database.',
        'Can you find the structural variants for the NOTCH1, NOTCH2, and NOTCH3 in the dbVar database?',
        'Look up the conservation scores for the SOX2, NANOG, and POU5F1 in the UCSC Genome Browser.',
        'Retrieve the methylation data for the CDKN2A, MGMT, and MLH1 from the Illumina Human Methylation database.',
        'Find the expression quantitative trait loci (eQTLs) for the GATA3, GATA4, and GATA6 in the GTEx database.',
        'Get the single nucleotide polymorphism (SNP) information for the APOE, LPL, and CETP from the dbSNP database.',
        'Look up the orthologs for the FOXP2, FOXP3, and FOXP4 in the OrthoDB database.',
        'Can you provide the evolutionary conservation data for the P53, P21, and P27 from the PhyloP database?',
        'Fetch the RNA-seq data for the MYOD1, MYOG, and MYF5 from the SRA database.',
        'Retrieve the fusion information for the EML4, ALK, and KIF5B from the ChimerDB database.',
        'Obtain the variant allele frequencies for the EGFR, KRAS, and BRAF from the ExAC database.',
        'Can you find the protein expression data for the TGFBR1, TGFBR2, and SMAD4 in the Human Protein Atlas?',
        'Look up the co-expression networks for the MDM4, CDK6, and CCND1 in the COEXPEDIA database.',
        'Retrieve the exon-intron structure for the BRIP1, RAD51, and RAD52 from the UCSC Genome Browser.',
        'Find the promoter sequences for the ABL1, BCR, and JAK2 in the EPD database.',
        'Get the regulatory elements for the MYC, MAX, and MAD in the ENCODE database.',
        'Look up the clinical trial information for the HER2, BRCA1, and BRCA2 in the ClinicalTrials.gov database.',
        'Can you provide the RNA binding protein interactions for the FMR1, FXR1, and FXR2 from the RBPDB database?',
        'Fetch the disease relationships for the GNAS, GNAQ, and GNA11 from the DisGeNET database.',
        'Retrieve the alternative splicing events for the SRSF1, SRSF2, and SRSF3 from the ASAP database.',
        'Obtain the enhancer regions for the HOXA1, HOXB1, and HOXD1 from the EnhancerAtlas database.',
        'Can you find the chromatin state segmentation for the TP63, TP73, and TP53 from the ENCODE database?',
        'Look up the proteomic data for the MAPK1, MAPK3, and MAPK8 in the ProteomicsDB database.',
        'Retrieve the binding sites for the transcription factors JUN, FOS, and ATF2 in the JASPAR database.',
        'Find the phenotypic information for the TERT, TERC, and DKC1 in the Human Phenotype Ontology (HPO) database.',
    ]
)
routeScrape = Route(
    name = 'SCRAPE',
    utterances = [
        'Find the most recent articles about TFs on bioRxiv.',
        'Find the most recent articles about transcription factors on bioRxiv.',
        'Find the most recent articles about TF on bioRxiv.',
        'Find the most recent articles about Transcription Factors on bioRxiv.',
        'Find the most recent articles about TFs on PubMed.',
        'Find the most recent articles about transcription factors on PubMed.',
        'Find the most recent articles about TF on PubMed.',
        'Find the most recent articles about Transcription Factors on PubMed.',
        'Search for the latest research on TFs on bioRxiv.',
        'Search for the latest research on transcription factors on bioRxiv.',
        'Search for the latest research on TF on bioRxiv.',
        'Search for the latest research on Transcription Factors on bioRxiv.',
        'Search for the latest research on TFs on PubMed.',
        'Search for the latest research on transcription factors on PubMed.',
        'Search for the latest research on TF on PubMed.',
        'Search for the latest research on Transcription Factors on PubMed.',
        'Get the most recent studies on TFs from bioRxiv.',
        'Get the most recent studies on transcription factors from bioRxiv.',
        'Get the most recent studies on TF from bioRxiv.',
        'Get the most recent studies on Transcription Factors from bioRxiv.',
        'Get the most recent studies on TFs from PubMed.',
        'Get the most recent studies on transcription factors from PubMed.',
        'Get the most recent studies on TF from PubMed.',
        'Get the most recent studies on Transcription Factors from PubMed.',
        'Look up the latest articles on TFs on bioRxiv.',
        'Look up the latest articles on transcription factors on bioRxiv.',
        'Look up the latest articles on TF on bioRxiv.',
        'Look up the latest articles on Transcription Factors on bioRxiv.',
        'Look up the latest articles on TFs on PubMed.',
        'Look up the latest articles on transcription factors on PubMed.',
        'Look up the latest articles on TF on PubMed.',
        'Look up the latest articles on Transcription Factors on PubMed.',
        'Retrieve the most recent publications on TFs from bioRxiv.',
        'Retrieve the most recent publications on transcription factors from bioRxiv.',
        'Retrieve the most recent publications on TF from bioRxiv.',
        'Retrieve the most recent publications on Transcription Factors from bioRxiv.',
        'Retrieve the most recent publications on TFs from PubMed.',
        'Retrieve the most recent publications on transcription factors from PubMed.',
        'Retrieve the most recent publications on TF from PubMed.',
        'Retrieve the most recent publications on Transcription Factors from PubMed.',
        'Find the newest articles on TFs on bioRxiv.',
        'Find the newest articles on transcription factors on bioRxiv.',
        'Find the newest articles on TF on bioRxiv.',
        'Find the newest articles on Transcription Factors on bioRxiv.',
        'Find the newest articles on TFs on PubMed.',
        'Find the newest articles on transcription factors on PubMed.',
        'Find the newest articles on TF on PubMed.',
        'Find the newest articles on Transcription Factors on PubMed.',
        'Can you find the latest research articles on cancer immunotherapy on PubMed?',
        'Look up recent papers on CRISPR gene editing on arXiv.',
        'Fetch the newest publications about single-cell RNA sequencing from bioRxiv.',
        'Search for the latest reviews on Alzheimer’s disease in PubMed.',
        'Can you get the most recent articles on machine learning in genomics from arXiv?',
        'Find the newest preprints on COVID-19 vaccines on bioRxiv.',
        'Look up the latest research on microbiome studies on PubMed.',
        'Retrieve the newest publications about gene therapy from arXiv.',
        'Search for recent papers on artificial intelligence in drug discovery on bioRxiv.',
        'Can you find the latest literature on epigenetics in cancer from PubMed?',
        'Fetch the most recent articles about protein structure prediction on arXiv.',
        'Look up the newest preprints on neural network applications in bioinformatics on bioRxiv.',
        'Find the latest research on stem cell therapies on PubMed.',
        'Can you search for the newest papers on deep learning for image analysis from arXiv?',
        'Retrieve the most recent publications on synthetic biology from bioRxiv.',
        'Look up recent articles about metabolic engineering on PubMed.',
        'Find the latest research on immunotherapy for cancer on arXiv.',
        'Can you fetch the newest publications on non-coding RNAs from bioRxiv?',
        'Search for the latest reviews on precision medicine in PubMed.',
        'Look up recent papers on gene editing technologies on arXiv.',
        'Find the most recent articles about viral genomics on bioRxiv.',
        'Can you get the newest literature on proteomics in disease research from PubMed?',
        'Fetch the latest research on computational biology on arXiv.',
        'Look up recent preprints on systems biology approaches on bioRxiv.',
        'Search for the newest articles on personalized medicine in PubMed.',
        'Can you find the latest publications on microbiome-host interactions from arXiv?',
        'Retrieve the newest papers on molecular diagnostics from bioRxiv.',
        'Look up recent research on genome-wide association studies on PubMed.',
        'Find the most recent reviews on CRISPR technology on arXiv.',
        'Can you search for the latest preprints on bioinformatics pipelines from bioRxiv?',
        'Fetch the newest articles on cancer biomarkers in PubMed.',
        'Look up the latest research on RNA therapeutics on arXiv.',
        'Find the most recent publications on transcriptomics on bioRxiv.',
        'Can you get the newest literature on cell signaling pathways from PubMed?',
        'Search for recent papers on genomic data analysis on arXiv.',
        'Look up the latest preprints on epigenetic modifications on bioRxiv.',
        'Fetch the newest articles about disease genomics on PubMed.',
        'Can you find the latest research on computational genomics from arXiv?',
        'Retrieve the most recent publications on high-throughput sequencing from bioRxiv.',
        'Look up recent reviews on bioinformatics algorithms in PubMed.',
        'Find the newest papers on cancer genomics on arXiv.',
        'Can you search for the latest preprints on microbial genomics from bioRxiv?',
        'Fetch the most recent articles on structural bioinformatics in PubMed.',
        'Look up the latest research on pharmacogenomics on arXiv.',
        'Find the newest publications on genetic circuits from bioRxiv.',
        'Can you get the latest literature on immunogenomics from PubMed?',
        'Search for recent papers on metagenomics on arXiv.',
        'Look up the most recent preprints on gene regulation on bioRxiv.',
        'Fetch the latest articles about RNA sequencing technologies in PubMed.',
        'Can you find the latest studies on machine learning for drug discovery on PubMed?',
        'Look up recent research articles on CRISPR-based diagnostics from arXiv.',
        'Fetch the newest publications about aging and longevity on bioRxiv.',
        'Search for the latest reviews on cardiovascular disease in PubMed.',
        'Can you get the most recent papers on deep learning in healthcare from arXiv?',
        'Find the latest preprints on gene expression profiling on bioRxiv.',
        'Look up the newest research on autoimmune diseases on PubMed.',
        'Retrieve the most recent publications about bioinformatics tools from arXiv.',
        'Search for recent papers on genome editing technologies on bioRxiv.',
        'Can you find the latest literature on cancer metabolism from PubMed?',
        'Fetch the newest articles on computational drug design from arXiv.',
        'Look up recent preprints on synthetic biology applications on bioRxiv.',
        'Find the latest research on infectious disease genomics on PubMed.',
        'Can you search for the newest papers on neural networks for genomics from arXiv?',
        'Retrieve the most recent publications on genetic epidemiology from bioRxiv.',
        'Look up recent articles about chromatin remodeling on PubMed.',
        'Find the latest research on bioinformatics databases on arXiv.',
        'Can you fetch the newest publications on non-invasive prenatal testing from bioRxiv?',
        'Search for the latest reviews on microbiome analysis in PubMed.',
        'Look up recent papers on genetic risk factors on arXiv.',
        'look up the new research in transcription factors on PubMed search'
        'Find the most recent articles about TFs in genomes on bioRxiv.',
        'Find the most recent articles about transcription factors in genomes on bioRxiv.',
        'Can you get the newest literature on cancer genetics from PubMed?',
        'Fetch the latest research on comparative genomics from arXiv.',
        'Look up recent preprints on computational methods in genomics on bioRxiv.',
        'Search for the newest articles on RNA sequencing data analysis in PubMed.',
        'Can you find the latest publications on protein-protein interactions from arXiv?',
        'Retrieve the newest papers on epigenomic profiling from bioRxiv.',
        'Look up recent research on disease biomarkers on PubMed.',
        'Find the most recent reviews on metagenomic analysis on arXiv.',
        'Can you search for the latest preprints on next-generation sequencing technologies from bioRxiv?',
        'Fetch the newest articles on gene function annotation in PubMed.',
        'Look up the latest research on systems genetics on arXiv.',
        'Find the most recent publications on cancer immunogenomics from bioRxiv.',
        'Can you get the newest literature on genomics of rare diseases from PubMed?',
        'Search for recent papers on chromosomal aberrations on arXiv.',
        'Look up the latest preprints on integrative genomics on bioRxiv.',
        'Fetch the newest articles about whole genome sequencing in PubMed.',
        'Can you find the latest research on gene-environment interactions from arXiv?',
        'Retrieve the most recent publications on population genomics from bioRxiv.',
        'Look up recent reviews on computational approaches in genomics in PubMed.',
        'Find the newest papers on genomic instability on arXiv.',
        'Can you search for the latest preprints on functional genomics from bioRxiv?',
        'Fetch the most recent articles on microbial community genomics in PubMed.',
        'Look up the latest research on evolutionary genomics on arXiv.',
        'Find the newest publications on epigenetic regulation from bioRxiv.',
        'Can you get the latest literature on genomic data integration from PubMed?',
        'Search for recent papers on personalized cancer treatment on arXiv.',
        'Look up the most recent preprints on data-driven genomics on bioRxiv.',
        'Fetch the latest articles about multi-omics data analysis in PubMed.',
        'Can you find the latest studies on machine learning for drug discovery?',
        'Look up recent research articles on CRISPR-based diagnostics.',
        'Fetch the newest publications about aging and longevity.',
        'Search for the latest reviews on cardiovascular disease.',
        'Can you get the most recent papers on deep learning in healthcare?',
        'Find the latest preprints on gene expression profiling.',
        'Look up the newest research on autoimmune diseases.',
        'Retrieve the most recent publications about bioinformatics tools.',
        'Search for recent papers on genome editing technologies.',
        'Can you find the latest literature on cancer metabolism?',
        'Fetch the newest articles on computational drug design.',
        'Look up recent preprints on synthetic biology applications.',
        'Find the latest research on infectious disease genomics.',
        'Can you search for the newest papers on neural networks for genomics?',
        'Retrieve the most recent publications on genetic epidemiology.',
        'Look up recent articles about chromatin remodeling.',
        'Find the latest research on bioinformatics databases.',
        'Can you fetch the newest publications on non-invasive prenatal testing?',
        'Search for the latest reviews on microbiome analysis.',
        'Look up recent papers on genetic risk factors.',
        'Find the most recent articles about structural variation in genomes.',
        'Can you get the newest literature on cancer genetics?',
        'Fetch the latest research on comparative genomics.',
        'Look up recent preprints on computational methods in genomics.',
        'Search for the newest articles on RNA sequencing data analysis.',
        'Can you find the latest publications on protein-protein interactions?',
        'Retrieve the newest papers on epigenomic profiling.',
        'Look up recent research on disease biomarkers.',
        'Find the most recent reviews on metagenomic analysis.',
        'Can you search for the latest preprints on next-generation sequencing technologies?',
        'Fetch the newest articles on gene function annotation.',
        'Look up the latest research on systems genetics.',
        'Find the most recent publications on cancer immunogenomics.',
        'Can you get the newest literature on genomics of rare diseases?',
        'Search for recent papers on chromosomal aberrations.',
        'Look up the latest preprints on integrative genomics.',
        'Fetch the newest articles about whole genome sequencing.',
        'Can you find the latest research on gene-environment interactions?',
        'Retrieve the most recent publications on population genomics.',
        'Look up recent reviews on computational approaches in genomics.',
        'Find the newest papers on genomic instability.',
        'Can you search for the latest preprints on functional genomics?',
        'Fetch the most recent articles on microbial community genomics.',
        'Look up the latest research on evolutionary genomics.',
        'Find the newest publications on epigenetic regulation.',
        'Can you get the latest literature on genomic data integration?',
        'Search for recent papers on personalized cancer treatment.',
        'Look up the most recent preprints on data-driven genomics.',
        'Fetch the latest articles about multi-omics data analysis.',
        'Find the newest studies on gene editing advancements.',
        'Can you look up recent research on precision medicine?',
        'What are the latest findings in cancer research?',
        'How many new studies on gene therapy have been published recently?',
        'What are the recent advancements in CRISPR technology?',
        'Recently, what has been discovered about Alzheimer’s disease?',
        'What are the new trends in machine learning for genomics?',
        'How many recent articles discuss the human microbiome?',
        'What are the current research focuses in stem cell therapy?',
        'Recently, what progress has been made in vaccine development?',
        'What are the latest innovations in personalized medicine?',
        'How many new publications are there on RNA sequencing?',
        'What are the recent discoveries in genetic engineering?',
        'Recently, what studies have been done on metabolic diseases?',
        'What are the current trends in bioinformatics research?',
        'How many new papers cover single-cell RNA sequencing?',
        'What are the most recent advancements in epigenetics?',
        'Recently, what has been published about infectious diseases?',
        'What are the latest findings in neurodegenerative diseases?',
        'How many new studies are there on gene expression?',
        'What are the recent developments in proteomics?',
        'Recently, what research has been done on cardiovascular diseases?',
        'What are the latest studies on cancer biomarkers?',
        'How many new publications are there on genomic data analysis?',
        'What are the current trends in synthetic biology?',
        'Recently, what advancements have been made in drug discovery?',
        'What are the latest findings in autoimmune diseases?',
        'How many recent papers focus on chromatin dynamics?',
        'What are the most recent developments in immunotherapy?',
        'Recently, what has been discovered in microbial genomics?',
        'What are the current focuses in computational biology?',
        'How many new studies are there on precision medicine?',
        'What are the latest innovations in high-throughput sequencing?',
        'Recently, what progress has been made in systems biology?',
        'What are the new trends in genetic risk analysis?',
        'How many recent articles discuss gene-environment interactions?',
        'What are the latest findings in rare disease genomics?',
        'Recently, what has been published about gene regulation?',
        'What are the current trends in cancer immunogenomics?',
        'How many new studies focus on non-coding RNAs?',
        'What are the recent advancements in multi-omics integration?',
        'Recently, what discoveries have been made in viral genomics?',
        'What are the latest findings in population genetics?',
        'How many new publications are there on protein interactions?',
        'What are the recent trends in epigenomic research?',
        'Recently, what has been done in the field of metabolic engineering?',
        'What are the latest studies on genetic epidemiology?',
        'How many new articles cover computational methods in genomics?',
        'What are the current focuses in cancer genomics?',
        'Recently, what advancements have been made in transcriptomics?',
        'What are the most recent developments in gene function annotation?',
        'How many recent papers discuss chromosomal abnormalities?',
        'What is new in cancer research?',
        'What is new in gene therapy?',
        'What is new in CRISPR technology?',
        'What is new in Alzheimer’s disease research?',
        'What is new in machine learning for genomics?',
        'What is new in human microbiome studies?',
        'What is new in stem cell therapy?',
        'What is new in vaccine development?',
        'What is new in personalized medicine?',
        'What is new in RNA sequencing?',
        'What is new in genetic engineering?',
        'What is new in metabolic disease research?',
        'What is new in bioinformatics?',
        'What is new in single-cell RNA sequencing?',
        'What is new in epigenetics?',
        'What is new in infectious disease research?',
        'What is new in neurodegenerative diseases?',
        'What is new in gene expression studies?',
        'What is new in proteomics?',
        'What is new in cardiovascular disease research?',
        'What is new in cancer biomarker discovery?',
        'What is new in genomic data analysis?',
        'What is new in synthetic biology?',
        'What is new in drug discovery?',
        'What is new in autoimmune disease research?',
        'What is new in chromatin dynamics?',
        'What is new in immunotherapy?',
        'What is new in microbial genomics?',
        'What is new in computational biology?',
        'What is new in precision medicine?',
        'What is new in high-throughput sequencing?',
        'What is new in systems biology?',
        'What is new in genetic risk analysis?',
        'What is new in gene-environment interaction studies?',
        'What is new in rare disease genomics?',
        'What is new in gene regulation?',
        'What is new in cancer immunogenomics?',
        'What is new in non-coding RNA research?',
        'What is new in multi-omics integration?',
        'What is new in viral genomics?',
        'What is new in population genetics?',
        'What is new in protein interaction research?',
        'What is new in epigenomic research?',
        'What is new in metabolic engineering?',
        'What is new in genetic epidemiology?',
        'What is new in computational methods in genomics?',
        'What is new in cancer genomics?',
        'What is new in transcriptomics?',
        'What is new in gene function annotation?',
        'What is new in chromosomal abnormality research?',
        'What is new in genomics and bioinformatics?',
        'What is new here?',
        'Is this actively worked on?',
        'Who currently does this?',
        'What is new in this area?',
        'search the latest transcription factor work on PubMed',
    ]
)
routeRAG = Route(
    name = 'RAG',
    utterances = [
        'What is the latest research on cancer genomics?',
        'Can you find articles about protein-protein interactions?',
        'Retrieve studies on RNA sequencing.',
        "I'm interested in recent research on computational biology.",
        'Find literature about genetic epidemiology.',
        'Search for papers on metagenomics.',
        'Can you fetch articles on personalized medicine?',
        'Retrieve studies on transcriptomics.',
        'What is the latest research on chromatin remodeling?',
        'Find articles discussing immunogenomics.',
        'Can you fetch papers on CRISPR-Cas9 applications?',
        'Retrieve literature about gene function annotation.',
        'I want to read about chromosomal abnormalities.',
        'Search for reviews on integrative genomics.',
        'Retrieve studies on cancer immunogenomics.',
        'What is the latest research on gene expression regulation?',
        'Can you find articles about stem cell therapy?',
        'Retrieve studies on infectious disease genomics.',
        "I'm interested in recent research on single-cell RNA sequencing.",
        'Find literature about drug discovery using machine learning.',
        'Search for papers on systems biology.',
        'Can you fetch articles on non-coding RNA function?',
        'Retrieve literature about rare disease genomics.',
        'What is the latest research on metabolic diseases?',
        'Find articles discussing computational methods in genomics.',
        'Retrieve studies on protein structure prediction.',
        'I want to read about RNA therapeutics.',
        'Search for papers on computational biology algorithms.',
        'Can you fetch articles on evolutionary genomics?',
        'Retrieve literature about pharmacogenomics.',
        'What is the latest research on epigenomic profiling?',
        'Find articles discussing genomic instability.',
        'Can you fetch papers on data-driven genomics?',
        'Retrieve studies on cancer genomics.',
        "I'm interested in recent research on personalized cancer treatment.",
        'Find literature about gene regulation networks.',
        'Can you fetch articles on gene editing advancements?',
        'Retrieve literature about cancer biomarkers.',
        'What is the latest research on gene-environment interactions?',
        'Find articles discussing high-throughput sequencing.',
        'Search for reviews on epigenetic regulation.',
        'Search for papers on multi-omics integration.',
        'Search for papers on viral genomics.',
        'Can you fetch articles on computational genomics?',
        'Retrieve studies on stem cell therapies.',
        "I'm interested in recent research on CRISPR-based diagnostics.",
        'Find literature about protein-protein interactions.',
        'Search for reviews on cardiovascular disease research.',
        'Can you fetch papers on synthetic biology?',
        'Retrieve literature about gene expression profiling.',
        'What are transcription factors?',
        'How do transcription factors regulate gene expression?',
        'What are the main types of transcription factors?',
        'Explain the role of transcription factors in cell differentiation.',
        'How do transcription factors bind to DNA?',
        'What is the structure of a transcription factor?',
        'How are transcription factors classified?',
        'Describe the mechanism of action of transcription factors.',
        'What are enhancer and silencer sequences in transcription factor binding?',
        'What role do transcription factors play in cancer?',
        'How do mutations in transcription factors lead to disease?',
        'What are the methods to study transcription factors?',
        'Explain the role of transcription factors in development.',
        'What are some common transcription factors in humans?',
        'How do transcription factors interact with other proteins?',
        'What is the difference between activators and repressors?',
        'How are transcription factors involved in signal transduction?',
        'What is a transcription factor binding site?',
        'How do transcription factors affect chromatin structure?',
        'Explain the concept of transcription factor networks.',
        'What are pioneer transcription factors?',
        'How do transcription factors regulate immune responses?',
        'What is the role of transcription factors in stem cells?',
        'Describe the role of transcription factors in metabolism.',
        'How do environmental factors influence transcription factor activity?',
        'What are the techniques for identifying transcription factor binding sites?',
        'How do transcription factors contribute to evolutionary processes?',
        'What is the role of transcription factors in epigenetics?',
        'How do transcription factors regulate stress responses?',
        'What are co-factors and how do they interact with transcription factors?',
        'Explain the role of transcription factors in neurological diseases.',
        'What is the significance of transcription factor binding motifs?',
        'How do transcription factors influence RNA polymerase activity?',
        'What are some examples of transcription factor families?',
        'How do post-translational modifications affect transcription factors?',
        'What is the role of transcription factors in plant biology?',
        'How do transcription factors regulate apoptosis?',
        'What are inducible transcription factors?',
        'Explain the role of transcription factors in muscle development.',
        'What is a transcription factor knockout experiment?',
        'How do transcription factors interact with microRNAs?',
        'What are synthetic transcription factors?',
        'How do transcription factors contribute to circadian rhythms?',
        'Describe the role of transcription factors in liver function.',
        'What is the function of transcription factors in adipogenesis?',
        'How are transcription factors involved in hypoxia response?',
        'What are transcription factor arrays?',
        'Explain the interaction between transcription factors and enhancers.',
        'What is the role of transcription factors in hematopoiesis?',
        'How do transcription factors regulate hormone response?',
        'what are some particulare genes discussed in: A comprehensive library of human transcription factors for cell fate engineering',
    ]
)
routeLoad = Route(
    name = 'LOAD',
    utterances = [
        'Load the CSV file "data.csv" from the local directory.',
        'Load the Excel file "data.xlsx" from the documents folder.',
        'Load the JSON file "data.json" from the downloads folder.',
        'Load the text file "data.txt" from the project directory.',
        'Load the image "image.jpg" from the images folder.',
        'Load the PDF file "document.pdf" from the documents directory.',
        'Load the XML file "data.xml" from the data folder.',
        'Load the HDF5 file "data.h5" from the datasets directory.',
        'Load the PNG image "picture.png" from the pictures folder.',
        'Load the GIF file "animation.gif" from the media directory.',
        'Load the TIFF image "image.tiff" from the images folder.',
        'Load the ZIP file "archive.zip" from the downloads folder.',
        'Load the CSV file "dataset.csv" from the data folder.',
        'Load the Excel file "workbook.xlsx" from the documents folder.',
        'Load the JSON file "data.json" from the data directory.',
        'Load the text file "text.txt" from the resources folder.',
        'Load the image "photo.jpg" from the pictures folder.',
        'Load the PDF file "report.pdf" from the reports directory.',
        'Load the XML file "file.xml" from the project directory.',
        'Load the HDF5 file "data.h5" from the datasets folder.',
        'Load the PNG image "image.png" from the media directory.',
        'Load the GIF file "animation.gif" from the animations folder.',
        'Load the TIFF image "image.tiff" from the images directory.',
        'Load the ZIP file "archive.zip" from the archive folder.',
        'Load the CSV data from the URL "http://example.com/data.csv".',
        'Load the Excel data from the URL "http://example.com/data.xlsx".',
        'Load the JSON data from the URL "http://example.com/data.json".',
        'Load the text data from the URL "http://example.com/data.txt".',
        'Load the image from the URL "http://example.com/image.jpg".',
        'Load the PDF document from the URL "http://example.com/document.pdf".',
        'Load the XML data from the URL "http://example.com/data.xml".',
        'Load the HDF5 data from the URL "http://example.com/data.h5".',
        'Load the PNG image from the URL "http://example.com/picture.png".',
        'Load the GIF animation from the URL "http://example.com/animation.gif".',
        'Load the TIFF image from the URL "http://example.com/image.tiff".',
        'Load the ZIP archive from the URL "http://example.com/archive.zip".',
        'Load the CSV file "file.csv" from the shared network drive.',
        'Load the Excel file "workbook.xlsx" from the company server.',
        'Load the JSON data "data.json" from the cloud storage.',
        'Load the text file "text.txt" from the external hard drive.',
        'Load the image "photo.jpg" from the USB drive.',
        'Load the PDF document "document.pdf" from the network location.',
        'Load the XML file "data.xml" from the remote server.',
        'Load the HDF5 data "data.h5" from the backup drive.',
        'Load the PNG image "image.png" from the network shared folder.',
        'Load the GIF animation "animation.gif" from the NAS device.',
        'Load the TIFF image "image.tiff" from the network drive.',
        'Load the ZIP archive "archive.zip" from the cloud storage.'
        'Load my data',
        'load this file',
        'bring up these data',
        'lets check out this file',
        'give me this file',
        'pull that up real quick',
        'lets look into that',
        '.csv',
        '.txt',
        '.tsv',
        'Load my data from the local directory.',
        'Load this file "data.csv" from the documents folder.',
        'Bring up these data stored in "data.json" from the downloads folder.',
        'Let\'s check out this file "document.pdf" from the project directory.',
        'Give me this file "image.jpg" from the images folder.',
        'Pull that up real quick, the Excel file "workbook.xlsx" from the documents directory.',
        'Let\'s look into that and load the JSON file "data.json" from the data folder.',
        'Load my data, the text file "text.txt" from the resources folder.',
        'Load this file "photo.jpg" from the pictures folder.',
        'Bring up these data, the PDF document "report.pdf" from the reports directory.',
        'Let\'s check out this file "file.xml" from the project directory.',
        'Give me this file, the HDF5 file "data.h5" from the datasets folder.',
        'Pull that up real quick, the PNG image "image.png" from the media directory.',
        'Let\'s look into that and load the GIF file "animation.gif" from the animations folder.',
        'Load my data from the URL "http://example.com/data.csv".',
        'Load this file from the URL "http://example.com/data.xlsx".',
        'Bring up these data from the URL "http://example.com/data.json".',
        'Let\'s check out this file from the URL "http://example.com/data.txt".',
        'Give me this file from the URL "http://example.com/image.jpg".',
        'Pull that up real quick, the PDF document from the URL "http://example.com/document.pdf".',
        'Let\'s look into that and load the XML data from the URL "http://example.com/data.xml".',
        'Load my data from the URL "http://example.com/data.h5".',
        'Load this file from the URL "http://example.com/picture.png".',
        'Bring up these data from the URL "http://example.com/animation.gif".',
        'Let\'s check out this file from the URL "http://example.com/image.tiff".',
        'Give me this file from the URL "http://example.com/archive.zip".',
        'Pull that up real quick, the CSV file "file.csv" from the shared network drive.',
        'Let\'s look into that and load the Excel file "workbook.xlsx" from the company server.',
        'Load my data from the cloud storage, the JSON data "data.json".',
        'Load this file from the external hard drive, the text file "text.txt".',
        'Bring up these data from the USB drive, the image "photo.jpg".',
        'Let\'s check out this file from the network location, the PDF document "document.pdf".',
        'Give me this file from the remote server, the XML file "data.xml".',
        'Pull that up real quick, the HDF5 data "data.h5" from the backup drive.',
        'Let\'s look into that and load the PNG image "image.png" from the network shared folder.',
        'Load my data from the NAS device, the GIF animation "animation.gif".',
        'Load this file from the network drive, the TIFF image "image.tiff".',
        'Bring up these data from the cloud storage, the ZIP archive "archive.zip".',
        'Let\'s check out this file, the CSV file "data.csv" from the local directory.',
        'Give me this file, the Excel file "workbook.xlsx" from the documents folder.',
        'Pull that up real quick, these data stored in "data.json" from the downloads folder.',
        'Let\'s look into that and load this file "document.pdf" from the project directory.',
        'Load my data, this file "image.jpg" from the images folder.',
        'Load this file "workbook.xlsx" from the documents directory.',
        'Bring up these data, this file "data.json" from the data folder.',
        'Let\'s check out this file "text.txt" from the resources folder.',
        'Give me this file "photo.jpg" from the pictures folder.',
        'Pull that up real quick, the PDF document "report.pdf" from the reports directory.',
        'Let\'s look into that and load the XML file "file.xml" from the project directory.',
        'pull that up',
        'lets see that data',
        'check out that file',
        'whats in that',
        'what data is in that',
    ]
)

def getRouter():
    encoder = HuggingFaceEncoder()
    routes = [routeGget, routeScrape, routeLoad, routeRAG]
    router = RouteLayer(encoder=encoder, routes=routes)    
    return router

routeData = Route(
    name = 'data',
    utterances = [
        'How can I filter rows based on a condition?',
        'What is the average value of a numeric column?',
        'Can you show me a summary of the dataset?',
        'How do I sort the data in ascending/descending order?',
        'What are the unique categories/values in a specific column?',
        'How can I group the data and calculate aggregations?',
        'Can you visualize the data in a chart or plot?',
        'What is the maximum/minimum value in the dataset?',
        'How do I handle missing or null values?',
        'Can you show me the top/bottom rows of the dataset?',
        'How can I find rows with specific text or pattern?',
        'What are the correlations between different columns?',
        'How do I create a pivot table or cross-tabulation?',
        'Can you calculate percentages or proportions?',
        'How can I export the dataset to a file?',
        'What are the steps to perform data cleaning?',
        'How do I detect and handle outliers in the data?',
        'Can you summarize statistical measures for numerical columns?',
        'How can I perform time series analysis on the data?',
        'What techniques can I use for feature engineering?',
        'How do I split the data into training and testing sets?',
        'What is the best way to handle categorical variables?',
        'How do I evaluate the performance of a model or analysis?',
        'Can you show me examples of data visualization?',
        'How can I calculate cumulative or rolling aggregates?',
        'What is the purpose of data normalization or standardization?',
        'How do I merge or join multiple datasets?',
        'Can you explain the concept of cross-validation?',
        'How can I automate data analysis or reporting tasks?',
        'What are the steps to prepare data for a machine learning model?',        
    ]
)

def getTableRouter():
    encoder = HuggingFaceEncoder()
    routes = [routeData]
    router = RouteLayer(encoder=encoder, routes=routes)    
    return router