function output = helloMATLAB()
    % Print "Hello World"
    disp('Hello World');
    
    % Explain that we are running MATLAB code from Python
    disp('This message is generated by running MATLAB code from Python.');
    output = 0;
end
